FROM mcr.microsoft.com/devcontainers/base:noble

COPY post-create.sh /usr/local/bin/post-create
RUN chmod +x /usr/local/bin/post-create

COPY post-start.sh /usr/local/bin/post-start
RUN chmod +x /usr/local/bin/post-start